### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by totora0155** [totora0155/app-reffist#1]
- [ ] presets
- [x] history
- [ ] delete bookmark
- [ ] swap bookmark
- [x] context menu
- [ ] setting window
- [ ] device embed  and that capture
- [ ] new window (target=_blank)
- [ ] add preset form
